### ISSUE TITLE
Setup failing on master

### ISSUE THREAD

**Issue by Hypnosphi** [paypal/glamorous#407]
After checking out the repo, and running `npm run setup --silent` according to `CONTRIBUTING.md`, I get following output:

```
$ npm -v
5.7.1
$ npm run setup --silent
+ node-darwin-x64@8.11.1
added 1 package in 2.215s
[fsevents] Success: "/Users/jetbrains/IdeaProjects/glamorous/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
husky
setting up Git hooks
done

Love Preact? You can now donate to our open collective:
 > https://opencollective.com/preact/donate
added 1464 packages from 670 contributors and updated 2 packages in 42.657s
[build-and-test] [react.cjs] 
[build-and-test] [react.cjs] src/cjs-entry.js → dist/glamorous.cjs.js...
[build-and-test] [react.esm] 
[build-and-test] [react.esm] src/index.js → dist/glamorous.esm.js...
[build-and-test] [preact.umd] 
[build-and-test] [preact.umd] src/umd-entry.js → preact/dist/glamorous.umd.js...
[build-and-test] [preact.esm] 
[build-and-test] [preact.esm] src/index.js → preact/dist/glamorous.esm.js...
[build-and-test] [preact.umd.min] 
[build-and-test] [preact.umd.min] src/umd-entry.js → preact/dist/glamorous.umd.min.js...
[build-and-test] [react.umd.min] 
[build-and-test] [react.umd.min] src/umd-entry.js → dist/glamorous.umd.min.js...
[build-and-test] [preact.cjs] 
[build-and-test] [preact.cjs] src/cjs-entry.js → preact/dist/glamorous.cjs.js...
[build-and-test] [react.umd] 
[build-and-test] [react.umd] src/umd-entry.js → dist/glamorous.umd.js...
[build-and-test] [react.cjs] [!] (babel plugin) Error: It looks like your Babel configuration specifies a module transformer. Please disable it. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
[build-and-test] [react.cjs] src/cjs-entry.js
[build-and-test] [react.cjs] Error: It looks like your Babel configuration specifies a module transformer. Please disable it. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
[build-and-test] [react.cjs]     at error (/Users/jetbrains/IdeaProjects/glamorous/node_modules/rollup/dist/rollup.js:168:15)
[build-and-test] [react.cjs]     at Object.error (/Users/jetbrains/IdeaProjects/glamorous/node_modules/rollup/dist/rollup.js:19382:21)
[build-and-test] [react.cjs]     at /Users/jetbrains/IdeaProjects/glamorous/node_modules/rollup/dist/rollup.js:19391:29
[build-and-test] [react.cjs]     at <anonymous>
[build-and-test] [react.cjs]     at process._tickCallback (internal/process/next_tick.js:188:7)
[build-and-test] [react.cjs]     at Function.Module.runMain (module.js:695:11)
[build-and-test] [react.cjs]     at startup (bootstrap_node.js:188:16)
[build-and-test] [react.cjs]     at bootstrap_node.js:609:3
[build-and-test] [react.cjs] 
[build-and-test] [react.cjs] cross-env BUILD_ROLLUP=true BUILD_FORMAT=cjs BUILD_MINIFY=false NODE_ENV=development BUILD_PREACT=false BUILD_NODE=false BUILD_REACT_NATIVE=false rollup --config exited with code 1
[build-and-test] --> Sending SIGTERM to other processes..
[build-and-test] [react.esm] [!] (babel plugin) Error: It looks like your Babel configuration specifies a module transformer. Please disable it. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
[build-and-test] [react.esm] src/index.js
[build-and-test] [react.esm] Error: It looks like your Babel configuration specifies a module transformer. Please disable it. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
[build-and-test] [react.esm]     at error (/Users/jetbrains/IdeaProjects/glamorous/node_modules/rollup/dist/rollup.js:168:15)
[build-and-test] [react.esm]     at Object.error (/Users/jetbrains/IdeaProjects/glamorous/node_modules/rollup/dist/rollup.js:19382:21)
[build-and-test] [react.esm]     at /Users/jetbrains/IdeaProjects/glamorous/node_modules/rollup/dist/rollup.js:19391:29
[build-and-test] [react.esm]     at <anonymous>
[build-and-test] [react.esm]     at process._tickCallback (internal/process/next_tick.js:188:7)
[build-and-test] [react.esm]     at Function.Module.runMain (module.js:695:11)
[build-and-test] [react.esm]     at startup (bootstrap_node.js:188:16)
[build-and-test] [react.esm]     at bootstrap_node.js:609:3
[build-and-test] [react.esm] 
[build-and-test] [react.esm] cross-env BUILD_ROLLUP=true BUILD_FORMAT=esm BUILD_MINIFY=false NODE_ENV=development BUILD_PREACT=false BUILD_NODE=false BUILD_REACT_NATIVE=false rollup --config exited with code 1
[build-and-test] [preact.esm] cross-env BUILD_ROLLUP=true BUILD_FORMAT=esm BUILD_MINIFY=false NODE_ENV=development BUILD_PREACT=true BUILD_NODE=false BUILD_REACT_NATIVE=false rollup --config exited with code 0
[build-and-test] [react.umd.min] cross-env BUILD_ROLLUP=true BUILD_FORMAT=umd BUILD_MINIFY=true NODE_ENV=production BUILD_PREACT=false BUILD_NODE=false BUILD_REACT_NATIVE=false rollup --config --sourcemap exited with code 0
[build-and-test] [react.umd] cross-env BUILD_ROLLUP=true BUILD_FORMAT=umd BUILD_MINIFY=false NODE_ENV=development BUILD_PREACT=false BUILD_NODE=false BUILD_REACT_NATIVE=false rollup --config --sourcemap exited with code 0
[build-and-test] [preact.umd.min] cross-env BUILD_ROLLUP=true BUILD_FORMAT=umd BUILD_MINIFY=true NODE_ENV=production BUILD_PREACT=true BUILD_NODE=false BUILD_REACT_NATIVE=false rollup --config --sourcemap exited with code 0
[build-and-test] [preact.cjs] cross-env BUILD_ROLLUP=true BUILD_FORMAT=cjs BUILD_MINIFY=false NODE_ENV=development BUILD_PREACT=true BUILD_NODE=false BUILD_REACT_NATIVE=false rollup --config exited with code 0
[build-and-test] [preact.umd] cross-env BUILD_ROLLUP=true BUILD_FORMAT=umd BUILD_MINIFY=false NODE_ENV=development BUILD_PREACT=true BUILD_NODE=false BUILD_REACT_NATIVE=false rollup --config --sourcemap exited with code 0
[build-and-test] npm run build-and-test --silent exited with code 1
--> Sending SIGTERM to other processes..
[lint] npm run lint --silent exited with code null
[test:cover] npm run test:cover --silent exited with code null

```

**Comment by kentcdodds** [comment]
Hmmmmmmm.... I'm not sure what's up. Will have to dig in a bit

**Comment by kentcdodds** [comment]
This project is now in an unmaintained status. Please see the README for more information.
